baseURL = "https://suvashkumar.xyz/"
languageCode = "en-us"
title = "Suvash Kumar"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Suvash Kumar"
description = "Developer & Blogger"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/suvash.png"

# Builder name
builtWith = "gohugo"

copyright = "Suvash Kumar"
# license = "CC BY-SA 4.0"
# licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#FF8833"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/suvash-kumar-544b5917b"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/suvashsumon"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/SuvashK13937007"

  [[params.socialIcons]]
  icon = "fa-facebook"
  title = "Facebook"
  url = "https://facebook.com/suvashkumar.sumon"

  [[params.socialIcons]]
  icon = "fa fa-envelope"
  title = "Email"
  url = "mailto:suvashkumar.naogaon@gmail.com"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

 [[menu.main]]
  name = "Categories"
  identifier = "categories"
  weight = 200
  url = "/categories/"

  [[menu.main]]
  name = "About Me"
  identifier = "about"
  weight = 300
  url = "/about-me/"

  [[menu.main]]
  name = "Terms & Conditions"
  identifier = "terms-and-conditions"
  weight = 400
  url = "/terms-and-conditions/"





[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
